- hosts: all
  become_user: daniilrubin

  pre_tasks:
    - name: "Install packages"
      package: "name={{ item }} state=present"
      with_items:
        - nvim
        - jq
        - tmux
        - stow
      become: true
      become_user: "{{ root_user }}"

  tasks:
    - name: Stow dotfiles
      command: stow -v --ignore='(vscode|yaml|ini|cfg|\.sh)' .

