- hosts: all
  become_user: daniilrubin

  pre_tasks:
    - name: "Install packages"
      package: "name={{ item }} state=present"
      with_items:
        - neovim
        - jq
        - tmux
        - stow
      become: true
      become_user: "{{ root_user }}"

  tasks:
    - name: Stow dotfiles
      command: stow -v --ignore='(vscode|yaml|ini|cfg|\.sh)' .

    - name: Install tmux plugin manager
      git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: ~/.tmux/plugins/tpm

