# Alacritty config
import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 180, lines = 60 }
decorations = "Buttonless"
padding = { x = 4, y = 4 }
opacity = 0.7
blur = true

[font]
size = 12.5
[font.normal]
family = "MesloLGS NF"

